### ISSUE TITLE
Could you please add this to wpackagist

### ISSUE THREAD

**Issue by sjoerdvermeijden** [gagan0123/shortcode-in-menus#3]

**Comment by gagan0123** [comment]
There's isn't anything that I need to do in order to make it available in wpackagist, instead it fetches the plugins by itself, all you need to do is 
`"require": {
        "wpackagist-theme/shortcode-in-menus":"*"
    }`

**Comment by sjoerdvermeijden** [comment]
Cool thanks!


________________________________
Van: Gagan Deep Singh <notifications@github.com>
Verzonden: maandag 17 juli 2017 14:50
Aan: gagan0123/shortcode-in-menus
CC: sjoerdvermeijden; Author
Onderwerp: Re: [gagan0123/shortcode-in-menus] Could you please add this to wpackagist (#3)


There's isn't anything that I need to do in order to make it available in wpackagist, instead it fetches the plugins by itself, all you need to do is
"require": { "wpackagist-theme/shortcode-in-menus":"*" }

**Comment by gagan0123** [comment]
Just corrected a typo in the above code, I used the wpackagist-theme instead of wpackagist-plugin

**Comment by sjoerdvermeijden** [comment]
Yes, i can now see it's available on wpackagist aswell. I must have also made a typo looking for it in the search bar.


Thank you very much!


________________________________
Van: Gagan Deep Singh <notifications@github.com>
Verzonden: maandag 17 juli 2017 14:55
Aan: gagan0123/shortcode-in-menus
CC: sjoerdvermeijden; Author
Onderwerp: Re: [gagan0123/shortcode-in-menus] Could you please add this to wpackagist (#3)


Just corrected a typo in the above code, I used the wpackagist-theme instead of wpackagist-plugin
